#create service for mlops depoyment in kubernetes
apiVersion: v1
kind: Service
metadata:
  name: mlopsservice
  labels:
    app: mlops
spec:
  ports:
  - port: 80  
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: mlops
  type: LoadBalancer

